apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata: 
  name: multi-triggers-consumer
  namespace: default
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          hello: world
      spec:
        containers:
        - name: multi-trigger-consumer
          image: tsuyoshiushio/kafka-consumer:0.6
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: keda-multitriggers-pod-secrets
        restartPolicy: Never
  pollingInterval: 30
  maxReplicaCount: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: tsushikafka.servicebus.windows.net:9093
      consumerGroup: $Default
      topic: workitems
      lagThreshold: '1'
    authenticationRef:
      name: kafka-trigger-auth
  - type: azure-queue
    metadata:
      queueName: queue
      queueLength: '2'
      connectionFromEnv: STORAGE_CONNECTION_STRING
      accountName: tsushistorage 
      cloud: AzurePublicCloud
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kafka-trigger-auth
  namespace: default
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password    
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
